<?php
/**
 * This file has been automaticaly generated by Pomm Cli package.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace Model\PommTest\PommTestSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Beta
 *
 * Structure class for relation beta.
 * This is the beta comment.
 *
 * beta_one:
 * This is the beta.one comment.
 *
 * @see RowStructure
 */
class Beta extends RowStructure
{
    /**
     * initialize
     *
     * @see RowStructure
     */
    protected function initialize()
    {
        $this
            ->setRelation('beta')
            ->setPrimaryKey(['beta_two', 'beta_one'])
            ->addField('beta_one', 'int4')
            ->addField('beta_two', 'int4')
            ->addField('beta_three', 'xml')
            ;
    }
}
