<?php
/**
 * This file has been automatically generated by Pomm's generator.
 * You MIGHT NOT edit this file as your changes will be lost at next
 * generation.
 */

namespace Model\PommTest\PommTestSchema\AutoStructure;

use PommProject\ModelManager\Model\RowStructure;

/**
 * Beta
 *
 * Structure class for relation "pomm_test"."beta".
 * This is the beta comment.
 *
 * beta_one:
 * This is the beta.one comment.
 *
 * @see RowStructure
 */
class Beta extends RowStructure
{
    /**
     * __construct
     *
     * Structure definition.
     *
     * @access public
     */
    public function __construct()
    {
        $this
            ->setRelation('"pomm_test"."beta"')
            ->setPrimaryKey(['beta_two', 'beta_one'])
            ->addField('beta_one', 'int4')
            ->addField('beta_two', 'int4')
            ->addField('beta_three', 'pomm_test.complex_type[]')
            ;
    }
}
